### ISSUE TITLE
컬러팔레트 모듈화 필요

### ISSUE THREAD

**Issue by cocosasa** [sdh20282/jetty-chart#40]
컬러 팔레트를 모듈화 해서 데모 사이트와 라이브러리에서 import 해서 쓸 수 있도록 추가하는 작업이 필요합니다.

먼저, 컬러 팔레트의 배열을 추가한 뒤 차트 별로 기본 컬러 팔레트를  import한 배열값으로 바꿔야 합니다.

**Comment by sdh20282** [comment]
완료했습니다!
